### PR TITLE
When MRI, change rendering engine of markdown (kramdown -> qiita-markdown)

### PR DESCRIPTION
**Pull request by sue445**
# Why?

[qiita-markdown](https://github.com/increments/qiita-markdown) is better than [kramdown](https://github.com/gettalong/kramdown) in markdown rendering
# Example
## Sample markdown
- https://gist.githubusercontent.com/sue445/a0d3f9e5177b2801fb41/raw/2e93016c2d74a8c99fdcbd0f4f607a1fe6446cf4/test.md
- https://gist.github.com/sue445/a0d3f9e5177b2801fb41
## Before (Use kramdown)

gistub-before
## After (Use qiita-markdown)

gistub-after
# Breaking changes
- If use qiita-markdown, requirements **ruby2.x+** :crying_cat_face: 
  - qiita-markdown support only ruby 2.x+
    - https://github.com/increments/qiita-markdown/blob/v0.8.0/qiita-markdown.gemspec#L19
  - jruby can not build [charlock_holmes](https://github.com/brianmario/charlock_holmes) (dependency of qiita-markdown)

### CODE REVIEW

**Comment by seratch** [comment]
Dropping CRuby 1.9 is fine but I'd like to avoid dropping JRuby becuase users especially in China are running Gistub on the JVM. Using kramdown instead when JRuby is preferred.

**Comment by sue445** [comment]
> Using kramdown instead when JRuby is preferred.

I see.

I changed implements at 3e872f6be97
Use both qiita-markdown(MRI) and kramdown(JRuby)

Please check again :bow:

**Comment by seratch** [comment]
Thanks. LGTM.

**Comment by sue445** [comment]
:heart_eyes:

**Comment by lukehorvat** [comment]
Hi @seratch, could you release a new version for this? Thanks.

**Pull request merged**
